### PR TITLE
Some changes to help the Integration into the IntelliJ AEM Tooling Pl…

### PR DESCRIPTION
**Pull request by schaefa**
…ugin

- Made the Project Root Path settable in the Config class
- Add a method to get feedback from the Config’s check configuration
- In MainApp delayed the creaction of the Web View / Engine
- Added guards to the Properties Loading in FIle DIrs Util
- Added a markdown about the aemdc.files folder

Signed-off-by: Andreas Schaefer <hea76404@adobe.com>

### CODE REVIEW

**Comment by mtstv** [comment]
Hi Andreas,
in the ATTENTION.md do you mean, that we should avoid to use folder name like "ui.apps"?
For example
/aemdc-files/component/component-js/files/**ui.apps**/src/main/content/jcr_root/apps/project/components/component-js

**Comment by schaefa** [comment]
I would assume you cannot  but as far as I know this is used as a file rather than a
class loader resource.

That said if you ever are going to access it through a class loader then a path like this
cannot be accessed with the dot in the  middle but must be access as ui/apps.

Not to mention that I don’t like the naming of core and ui.apps. I never worked in a
project in the past 5 years that had a naming like that because we used multiple
bundles and content packages. But then again I never used a generation tool
like aemdc because the setup of a Maven project is so important than a proper
setup is worth the time to do it by hand.

Cheers - Andy Schaefer

**Comment by schaefa** [comment]
Made Marat the reviewer. Merged in the latest changes from master and made sure that the aemdcgui.xml is loaded from the root folder.

**Comment by mtstv** [comment]
thanks for contribution!

**Comment by schaefa** [comment]
Looks good, thanks.

**Pull request merged**
